[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = odoo        ; K8s service name for PostgreSQL
db_port = 5432
db_user = odoo
db_password = admin       ; Use K8s secret in production
db_name = odoo
http_port = 8069

